# Generated by Django 3.2.9 on 2021-12-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_options'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test', verbose_name='Тест'),
        ),
    ]
