# Generated by Django 3.2.9 on 2021-12-03 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('step', '0002_step_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasssedUserStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Кол-во баллов за тест')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='step.step', verbose_name='Шаг')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пройденные шаги пользователя',
                'verbose_name_plural': 'Пройденные шаги пользователя',
                'ordering': ('score',),
            },
        ),
    ]
