# Generated by Django 3.2.9 on 2021-12-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_auto_20211203_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
