# Generated by Django 3.2.9 on 2021-12-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_alter_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='award',
            field=models.CharField(default='fuel', max_length=20, verbose_name='Тип награды'),
        ),
        migrations.AddField(
            model_name='step',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
