# Generated by Django 3.2.9 on 2021-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0010_auto_20211204_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Пройден'),
        ),
    ]
