# Generated by Django 3.2.9 on 2021-12-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('name',), 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
