# Generated by Django 3.2.9 on 2021-12-03 13:04

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_file',
            field=models.BooleanField(default=False, verbose_name='Загрузка документов'),
        ),
        migrations.AddField(
            model_name='question',
            name='radio_button',
            field=models.BooleanField(default=False, verbose_name='radio button'),
        ),
        migrations.AddField(
            model_name='question',
            name='treasure',
            field=models.BooleanField(default=False, verbose_name='Ценности поле'),
        ),
        migrations.AddField(
            model_name='question',
            name='treasure_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, verbose_name='Ценности'), blank=True, default=list, null=True, size=None, verbose_name='Ценность'),
        ),
    ]
