# Generated by Django 3.2.9 on 2021-12-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20211203_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='treasure_list',
        ),
    ]
