# Generated by Django 3.2.9 on 2021-12-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.project', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Справочник документации',
                'verbose_name_plural': 'Справочники документации',
                'ordering': ('name',),
            },
        ),
    ]
