# Generated by Django 3.2.9 on 2021-12-03 05:29

import apps.account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('role_in_team', models.CharField(choices=[('Аналитик', 'Аналитик'), ('Тестировщик', 'Тестировщик'), ('Тимлид', 'Тимлид'), ('Разработчик', 'Разработчик')], max_length=50, verbose_name='Роль в команде')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Личное описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Фото')),
                ('stack', models.TextField(blank=True, null=True, verbose_name='Стэк')),
                ('number_test_scores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество баллов за тесты')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team', verbose_name='Команда')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('name',),
            },
            managers=[
                ('objects', apps.account.models.UserManager()),
            ],
        ),
    ]
