# Generated by Django 3.2.9 on 2021-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_number_test_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fuels',
            field=models.PositiveIntegerField(default=0, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='user',
            name='rockets',
            field=models.PositiveIntegerField(default=0, verbose_name='Модули ракеты'),
        ),
    ]
