# Generated by Django 3.2.9 on 2021-12-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211204_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='humans',
            field=models.PositiveIntegerField(default=0, verbose_name='Экипаж'),
        ),
    ]
